In [22]:
import numpy as np

A = np.random.randint(9, size = (4, 5))

print('', A, '\n')

numrows = 4
numcols = 5

for col in range(numcols):
    for row in range(col + 1, numrows):
        print(col, row)
        A[row] = A[row] - (A[row, col]/A[col, col]) * A[col]
        
print('\n', A)

 [[5 6 4 3 3]
 [3 6 7 8 4]
 [5 8 6 7 0]
 [3 7 5 8 6]] 

0 1
0 2
0 3
1 2
1 3
2 3

 [[ 5  6  4  3  3]
 [ 0  2  4  6  2]
 [ 0  0 -2 -2 -5]
 [ 0  0  0  1 11]]
