## P1

In [34]:
import numpy as np
import math 

def GaussianElimination(A):

    print('Original\n', A, '\n')

    numrows = len(A)    # Number of rows
    numcols = len(A[0]) # Number of columns

    # Gaussian Elimination
    for col in range(numcols - 1):           
        for row in range(col + 1, numrows):
            # print(A, '\n')
            A[row] = A[row] - (A[row, col]/A[col, col]) * A[col]
 
    print('Upper Triangular', '\n', A, '\n')

    # Make solution array
    x = np.array([0.0,0.0,0.0,0.0])   
        
    # Backsub
    for i in range(numrows - 1, -1, -1): 
        hold = 0.0
        for j in range(i + 1, numrows): 
            hold = hold + A[i,j] * x[j]
        x[i] = (A[i, numcols - 1] - hold) / A[i, i]
        
    return x

In [35]:
A = np.array([[6,5,6,5,7], 
              [5,6,7,0,2],
              [3,0,0,1,6], 
              [6,7,8,2,1]])

In [36]:
GaussianElimination(A)

Original
 [[6 5 6 5 7]
 [5 6 7 0 2]
 [3 0 0 1 6]
 [6 7 8 2 1]] 

Upper Triangular 
 [[  6   5   6   5   7]
 [  0   1   2  -4  -3]
 [  0   0   1  -9  -4]
 [  0   0   0 -13  -8]] 



array([ 2.12820513, -3.61538462,  1.53846154,  0.61538462])

In [37]:
import numpy as np
import math 

A = np.array([[math.pi             , -math.exp(1) , math.sqrt(2)  , -math.sqrt(3) , math.sqrt(11)], 
              [math.pow(math.pi, 2), math.exp(1)  , -math.exp(2)  , (3.0/7.0)     , 0            ],
              [math.sqrt(5)        , -math.sqrt(6), 1             , -math.sqrt(2) , math.pi      ], 
              [math.pow(math.pi, 3), math.exp(2)  , -math.sqrt(7) , (1.0/9.0)     , math.sqrt(2)]])

print('Original\n', A, '\n')

numrows = 4
numcols = 5

for col in range(numcols - 1):
    
    # Pivoting
    maxRow = np.argmax(abs(A[col:numrows, col]))
    temp = A[maxRow + col].copy()
    A[maxRow + col] = A[col]
    A[col] = temp
    
    # Gaussian Elimination
    for row in range(col + 1, numrows):
        # print(A, '\n')
        A[row] = A[row] - (A[row, col]/A[col, col]) * A[col]
        
print('Upper Triangular', '\n', A, '\n')
 
# Make solution array
x = np.array([0.0,0.0,0.0,0.0])
        
# Backsub
for i in range(numrows - 1, -1, -1):
    hold = 0.0
    for j in range(i + 1, numrows): 
        hold = hold + A[i,j] * x[j]
    x[i] = (A[i, numcols - 1] - hold) / A[i, i]
    
for z in range(4):
    print('\nX[',z,'] =', x[z])

Original
 [[  3.14159265  -2.71828183   1.41421356  -1.73205081   3.31662479]
 [  9.8696044    2.71828183  -7.3890561    0.42857143   0.        ]
 [  2.23606798  -2.44948974   1.          -1.41421356   3.14159265]
 [ 31.00627668   7.3890561   -2.64575131   0.11111111   1.41421356]] 

Upper Triangular 
 [[ 31.00627668   7.3890561   -2.64575131   0.11111111   1.41421356]
 [  0.          -3.46694974   1.68228422  -1.74330872   3.173335  ]
 [  0.           0.          -6.36915932   0.20902864  -0.1149054 ]
 [  0.           0.           0.           0.06900167   0.3144408 ]] 


X[ 0 ] = 0.788393791119

X[ 1 ] = -3.12541369935

X[ 2 ] = 0.167596598918

X[ 3 ] = 4.55700258101
