In [7]:
import numpy as np

In [8]:
A = np.array([[], [], [], []])

In [10]:
A

array([[  1,  -3,   1,   4],
       [  2,  -8,   8,  -2],
       [ -6,   3, -15,   9]])

In [11]:
A.shape

(3, 4)

In [13]:
A.shape[0]

3

In [14]:
A.shape[1]

4

In [15]:
A[0]

array([ 1, -3,  1,  4])

In [16]:
A[0, 1:]

array([-3,  1,  4])

In [19]:
A[1:3, 2]

array([  8, -15])

In [20]:
x = np.zeros([3, 1])

In [21]:
x

array([[ 0.],
       [ 0.],
       [ 0.]])

In [28]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [27]:
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

In [26]:
list(range(5, -1, -1))

[5, 4, 3, 2, 1, 0]

In [29]:
A

array([[  1,  -3,   1,   4],
       [  2,  -8,   8,  -2],
       [ -6,   3, -15,   9]])

In [33]:
A[1] = A[1] - (2./1.)*A[0]
A

array([[  1,  -3,   1,   4],
       [  7,   9,  25, -38],
       [ -6,   3, -15,   9]])

In [36]:
A = np.random.randint(4, size = (3,3))
B = np.random.randint(4, size = (3,3))
x = np.random.randint(4, size = (3,1))

In [37]:
B

array([[2, 3, 1],
       [2, 2, 1],
       [1, 3, 1]])

In [38]:
np.dot(A,x)

array([[7],
       [6],
       [7]])

In [39]:
A + B

array([[3, 5, 2],
       [5, 2, 1],
       [2, 4, 4]])